#!/usr/bin/env bash

if [ ! -z "$WWWUSER" ]; then
    usermod -u $WWWUSER brightmoon
fi

if [ ! -d /.composer ]; then
    mkdir /.composer
fi

chmod -R ugo+rw /.composer

apachectl -D FOREGROUND

exec /usr/bin/supervisord -c /etc/supervisor/conf.d/supervisord.conf
exec /usr/sbin/apache2
